### ISSUE TITLE
ply number = option ?!

### ISSUE THREAD

**Issue by tissatussa** [herohde/morlock#1]
hi, i managed to play with your TuroChamp in CuteChess on Linux :

![morlock_in_cutechess](https://user-images.githubusercontent.com/1109281/189904963-78a88743-b68e-448f-a451-e12f7956fc31.png)

i'm not familiar with go, but i see this code in main.go :

```
var (
    ply = flag.Int("ply", 2, "Search depth limit (zero if no limit)")
)
```

when i change the ply value to '6' or even more, TuroChamp indeed seems to play differently and thinks longer .. i guess you could make this parameter into a CuteChess UCI option .. that would be nice .. or did you abandon this project ? I find very few implementations of the TuroChamp method / counting, in any language - Haskell, Python, .NET, but not many chess programmers seem to be interested, i wonder.

-i'm on Xubuntu 22.04-

**Comment by herohde** [comment]
Hi there -- that value is defines a command line parameter. You can pass "--ply=N" as a command line argument to set the default search depth instead of changing the code. It also supports the "depth" parameter for the "go" UCI command to set a maximum search depth, which -- If set for a given search -- overrides the default. Given UCI native support for search depth, a separate UCI option would be redundant.

The project is not abandoned, just not under active development.
